import hashlib
import json
import struct
from typing import Any

import yaml


ARTIFACT_MAGIC = b"QTM1"
LAB_ARTIFACT_SALT = "quantum-workflow-labs-2026"


def build_model_binary(artifact_id: str, model_id: str, version: str, size_bytes: int) -> bytes:
    header = ARTIFACT_MAGIC + struct.pack("<I", size_bytes)
    identity = f"{artifact_id}|{model_id}|{version}|{LAB_ARTIFACT_SALT}".encode()
    digest = hashlib.sha256(identity).digest()
    payload = bytearray(header + digest)
    block = 32
    counter = 0
    while len(payload) < size_bytes:
        seed = hashlib.sha256(digest + counter.to_bytes(block, "big")).digest()
        payload.extend(seed)
        counter += 1
    return bytes(payload[:size_bytes])


def sha256_hex(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def build_metrics_json(metrics: dict[str, float]) -> bytes:
    document = {
        "auc": metrics.get("auc"),
        "f1": metrics.get("f1"),
        "precision": metrics.get("precision"),
        "recall": metrics.get("recall"),
        "psi": metrics.get("psi"),
    }
    return (json.dumps(document, indent=2, sort_keys=True, ensure_ascii=False) + "\n").encode("utf-8")


def build_model_card_md(card: dict[str, Any]) -> bytes:
    lines = [
        f"# Model Card - {card['modelo_id']} v{card['versao']}",
        "",
        "Fiction lab document generated by the Quantum Commerce Workflow Labs API.",
        "",
        "## Purpose",
        "",
        str(card.get("purpose") or ""),
        "",
        "## Owner",
        "",
        str(card.get("owner") or ""),
        "",
        "## Dataset",
        "",
        str(card.get("dataset") or ""),
        "",
        "## Limitations",
        "",
        str(card.get("limitations") or ""),
        "",
        "## PII documented",
        "",
        str(card.get("pii_documented") or ""),
        "",
        "## Dependencies",
        "",
        str(card.get("dependencies") or ""),
        "",
        "## Approvals",
        "",
        str(card.get("approvals") or ""),
        "",
    ]
    return "\n".join(lines).encode("utf-8")


def build_schema_yaml(schema: dict[str, Any]) -> bytes:
    return yaml.safe_dump(schema, sort_keys=True, allow_unicode=True).encode("utf-8")
